sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - main

php:
  - 5.6

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"
  - docker-compose -f docker-compose.phpunit.yml run --rm wordpress_phpunit  phpdbg -qrr /usr/local/bin/phpunit -c /app/phpunit.xml --coverage-clover=/app/clover.xml --coverage-html=/app/coverage

script:
  - phpunit --coverage-text --coverage-clover=coverage.cloverphpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
