sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.6

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"

script:
  - phpunit
  - WP_MULTISITE=1 phpunit
