version: "3"

services:
  wordpress_phpunit:
    image: "rahulprajapati/phpunit:latest"
    volumes:
      - ".:/app"
      - "testsuite:/tmp"
  mysql_phpunit:
    image: "mariadb:10.2"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress_test"
      MYSQL_ROOT_PASSWORD: ""

volumes:
  testsuite: {}
